
osx_image: xcode10.1
language: swift
os: osx

xcode_workspace: AnyFormatKit.xcworkspace
xcode_scheme: 
  - AnyFormatKit
  - AnyFormatKitTests
  - iOS Example

branches:
  only:
    - master
    - develop

script: ./run-tests.sh

notifications:
  email:
    recipients:
      - luximetr.notification@gmail.com
    on_success: always
    on_failure: always